;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	comment-line
	dired-do-copy
	electric-newline-and-maybe-indent
	end-of-buffer
	forward-sexp
	indent-for-tab-command
	kill-region
	markdown-beginning-of-line
	mc--replace-region-strings-1
	org-cycle
	org-delete-char
	org-end-of-line
	org-metaleft
	org-metaright
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	backward-sentence
	describe-key
	dired-do-chmod
	dired-do-compress-to
	forward-sentence
	))
